#!/bin/bash

HOSTNAME=$(hostname)
TOPIC=U01.sensors.heartbeat
HUB=geekhub-1:8082

while true; do
curl 	-X POST \
	-H "Content-Type: application/vnd.kafka.json.v2+json" \
	-H "Accept: application/vnd.kafka.v2+json" \
	--data "{\"records\":[{\"value\":{ \"time\":\"$(date)\", \"hostname\": \"${HOSTNAME}\"}}]}" http://${HUB}/topics/${TOPIC}
	
	echo "wait 10 seconds"
	sleep 10
done;
