#!/bin/bash

FREQ=1

while [[ $# > 1 ]]
do
key="$1"

case $key in
    --exec)
    EXEC="$2"
    shift # past argument
    ;;
    --freq)
    FREQ="$2"
    shift # past argument
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

SLEEP=$( echo "scale=5; 1.0 / $FREQ" | bc)
while true; do
    $EXEC
	sleep $SLEEP
done;
